### ISSUE TITLE
Push to Nuvola Player project

### ISSUE THREAD

**Issue by skyghis** [tiliado/nuvola-app-plex#1]
Part of the integration request for Plex service to Nuvola 3.

**Comment by fenryxo** [comment]
Hello. Thanks for your work. Will take a look at it later in July.

**Comment by fenryxo** [comment]
Hello. Code looks great, but there are still a few minor issues that need fixing:

**metadata.json**

* Change `name` to `Plex Music`.

**integrate.js**

* It might be handy to create a function `_getPlayerElements()` to avoid a code duplication at lines 111-119 & 152-160.
```
WebApp._getPlayerElements = function()
{
    var elements = {"player": document.querySelector(".player.music")};
    if (elements.player)
    {
        elements.play = playerElement.querySelector(".play-btn");
        elements.pause...; elements.previous...; elements.next...;
    }
    else
    {
        elements.shuffle = document.querySelector(".action-bar .play-shuffled-btn");
    }
    return elements;
}
```

**README.md**

* I would use "Plex Music" instead of plain "Plex".

**Comment by skyghis** [comment]
Thanks for the review.
All points should be fixed, waiting for your approval before closing the issue.

**Comment by fenryxo** [comment]
Great. It is now necessary to [transfer your repository](https://help.github.com/articles/transferring-a-repository/) to [Plex Music team](https://github.com/orgs/tiliado/teams/nuvola-plex-music) in [Tiliado organization](https://github.com/tiliado). Ping me when the transfer is done and I'll create packages for Debian/Ubuntu/Fedora. I'll close this ticket once the packages with your web app script are uploaded to the package repository.

**Comment by skyghis** [comment]
Repository transfer done.
Thanks.

**Comment by fenryxo** [comment]
Hello. I will create packages in batch with other web app scripts to be packaged this month. Hopefully next weekend.

**Comment by fenryxo** [comment]
Packages has with Plex Music have been released.
